### ISSUE TITLE
New sqlmap configuration

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#45]
I need people to test the new sqlmap configuration and check for issues with it. I'm not 100% sure if it will extract `Python 3.x.x` or not, but it should. So find the problems and let me know. Thanks guys.

**Comment by Ekultek** [comment]
From #46 


## Issue/Enhancement/Question (be specific)
Hi there,

I've installed your tool in ParrotOS and when I try to execute it i had this message:

## Exact error message/Enhancement information
```
/home/user/tools/whitewidow/lib/helpers/sqlmap_config_helper.rb:13:in `find_python_env_var': undefined method `split' for nil:NilClass (NoMethodError)
	from /home/jask/tools/whitewidow/lib/imports/constants_and_requires.rb:59:in `<top (required)>'
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'
```

## Steps to reproduce if applicable or steps on what should be done
cd /home/user/tools/whitewidow

## Search query if applicable (please use exact search query)
ruby whitewidow.rb -d

## User agent (if applicable)


## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
I can't get it.

## Ruby version number (run ruby --version)
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

## Labels

 - [X] Bug
 - [ ] Encoding
 - [ ] User agent
 - [ ] Enhancement
 - [ ] Question
 - [ ] Email request

Thanks a lot!

More info from #46 

Of course :) 

- **What is the command you where running when you received the error?**
```
ruby whitewidow.rb -h 
ruby whitewidow.rb -d
```
- **Did you clone whitewidow from the repo within the last few days?**
Yes, I've cloned it yesterday.
```
ls -l
total 4
drwxr-xr-x 9 jask jask 4096 Dec 30 01:27 white widow
```
- **Run printenv post the output**
```
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LANG=en_US.UTF-8
GDM_LANG=en_US.utf8
DISPLAY=:0
GTK_OVERLAY_SCROLLING=0
COLORTERM=truecolor
XDG_VTNR=7
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=2
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/jask
USER=jask
DESKTOP_SESSION=lightdm-xsession
PWD=/home/jask/tools
HOME=/home/jask
SSH_AGENT_PID=1406
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/mate:/usr/local/share/:/usr/share/
MATE_DESKTOP_SESSION_ID=this-is-deprecated
XDG_SESSION_DESKTOP=lightdm-xsession
TERM=xterm
SHELL=/bin/bash
VTE_VERSION=4601
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=MATE
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
SHLVL=1
XDG_SEAT=seat0
LANGUAGE=en_US:en
WINDOWID=46137350
GDMSESSION=lightdm-xsession
LOGNAME=jask
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/jask/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/jask/local/bin
SESSION_MANAGER=local/parrot:@/tmp/.ICE-unix/1348,unix/parrot:/tmp/.ICE-unix/1348
OLDPWD=/home/jask/tools/whitewidow
_=/usr/bin/printenv

```
- **Run python --version post the output**
Python 2.7.13

**Comment by Ekultek** [comment]
Closing this issue. New configuration will be pushed next update

**Comment by Ekultek** [comment]
Reopening this because I need to fix some stuff in it
