### ISSUE TITLE
SoUNTZP uninitialized constant SEARCH_QUERY

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#51]
## Issue/Enhancement/Question (be specific)
Getting error: uninitialized constant SEARCH_QUERY

## Exact error message/Enhancement information
uninitialized constant SEARCH_QUERY

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true}

## Search query if applicable (please use exact search query)
inurl:/sourcesinurl:/join.php?FORM[url]=owned&CONFIG[captcha]=1&CONFIG[path]= Aardvark TopSites

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
1.9.14.27

## Ruby version number (run ruby --version)
2.3.1

## Error log information
2017-04-07
["/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/home/ekultek/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:41:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-04-07
---
["whitewidow.rb:66:in `<main>'"]
["whitewidow.rb:66:in `<main>'"]
---
2017-04-07
["/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/home/ekultek/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:41:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-04-07
---
["whitewidow.rb:66:in `<main>'"]
["whitewidow.rb:66:in `<main>'"]
---

**Comment by Ekultek** [comment]
Fixed in the latest push
