### ISSUE TITLE
Getting error: undefined method `q=' for nil:NilClass

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#56]
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--

## Issue/Enhancement/Question (be specific)
Getting error: undefined method `q=' for nil:NilClass

## Exact error message/Enhancement information
undefined method `q=' for nil:NilClass

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true}

## Search query if applicable (please use exact search query)
default.php?itemnav=

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0

## Ruby version number (run ruby --version)
2.4.0

## Error log information
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
[]
---
2017-05-03
["/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:44:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
---
["whitewidow.rb:66:in `<main>'"]
["whitewidow.rb:66:in `<main>'"]
---
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---

**Comment by Ekultek** [comment]
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--

## Issue/Enhancement/Question (be specific)
Getting error: undefined method `q=' for nil:NilClass

## Exact error message/Enhancement information
undefined method `q=' for nil:NilClass

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true}

## Search query if applicable (please use exact search query)
intitle:"marketing".php?id= title:join


## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0

## Ruby version number (run ruby --version)
2.4.0

## Error log information
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
[]
---
2017-05-03
["/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:44:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---

**Comment by Ekultek** [comment]
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--

## Issue/Enhancement/Question (be specific)
Getting error: undefined method `q=' for nil:NilClass

## Exact error message/Enhancement information
undefined method `q=' for nil:NilClass

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true, :proxy=>"61.5.207.102:80"}

## Search query if applicable (please use exact search query)
print.php?base_dir=


## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0

## Ruby version number (run ruby --version)
2.4.0

## Error log information
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---

**Comment by Ekultek** [comment]
No idea, working on it. Probably has something to do with the search query not being accepted by mechanize.

**Comment by Ekultek** [comment]
IDEA:
 - Create a test to see if the search query fails or not, if it doesn't continue, if it does then grab another one and log the one that's causing the error

**Comment by Ekultek** [comment]
Fixed via a1dc7ed
