### ISSUE TITLE
Getting error: 503 => Net::HTTPServiceUnavailable

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#57]
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--

## Issue/Enhancement/Question (be specific)
Getting error: 503 => Net::HTTPServiceUnavailable for http://ipv4.google.com/sorry/index?continue=http://www.google.com/search%3Fhl%3Den%26source%3Dhp%26biw%3D%26bih%3D%26q%3Dpadrao.php%253Fpname%253D%250A%26btnG%3DGoogle%2BSearch%26gbv%3D1%26safe%3Dstrict&hl=en&q=EgRhTWgSGOvBp8gFIhkA8aeDS7sRcuOyvRb0V4EYqCc_oESrsWbwMgNyY24 -- unhandled response

## Exact error message/Enhancement information
503 => Net::HTTPServiceUnavailable for http://ipv4.google.com/sorry/index?continue=http://www.google.com/search%3Fhl%3Den%26source%3Dhp%26biw%3D%26bih%3D%26q%3Dpadrao.php%253Fpname%253D%250A%26btnG%3DGoogle%2BSearch%26gbv%3D1%26safe%3Dstrict&hl=en&q=EgRhTWgSGOvBp8gFIhkA8aeDS7sRcuOyvRb0V4EYqCc_oESrsWbwMgNyY24 -- unhandled response

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true, :proxy=>"97.77.104.22:80"}

## Search query if applicable (please use exact search query)
padrao.php?pname=

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0

## Ruby version number (run ruby --version)
2.4.0

## Error log information
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
[]
---
2017-05-03
["/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:44:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---

**Comment by Ekultek** [comment]
The IP has been blocked by Google temporarily
