### ISSUE TITLE
Getting error: too many connection resets

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#58]
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--

## Issue/Enhancement/Question (be specific)
Getting error: too many connection resets (due to end of file reached - EOFError) after 1 requests on 14403200, last used 10.30447847 seconds ago

## Exact error message/Enhancement information
too many connection resets (due to end of file reached - EOFError) after 1 requests on 14403200, last used 10.30447847 seconds ago

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true, :proxy=>"61.5.207.102:80"}

## Search query if applicable (please use exact search query)
summary.php?PID=

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0

## Ruby version number (run ruby --version)
2.4.0

## Error log information
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
[]
---

**Comment by Ekultek** [comment]
The proxy URL is bad
