### ISSUE TITLE
Getting error: uninitialized constant SEARCH_QUERY

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#59]
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--

## Issue/Enhancement/Question (be specific)
Getting error: uninitialized constant SEARCH_QUERY

## Exact error message/Enhancement information
uninitialized constant SEARCH_QUERY

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true}

## Search query if applicable (please use exact search query)
inurl:/modulesinurl:/vwarinurl:/admininurl:/admin.php?vwar_root=index.php?loc=

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0

## Ruby version number (run ruby --version)
2.4.0

## Error log information
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
[]
---
2017-05-03
["/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/home/baal/.rvm/gems/ruby-2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:44:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
---
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["/home/baal/bin/ruby/whitewidow/lib/whitewidow/scanner.rb:43:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2017-05-03
---
["whitewidow.rb:66:in `<main>'"]
["whitewidow.rb:66:in `<main>'"]
---

**Comment by Ekultek** [comment]
Bad dork query, will be fixed next push

**Comment by Ekultek** [comment]
Haven't seen in a few days, closing
