### ISSUE TITLE
cannot load such file -- mechanize 

### ISSUE THREAD

**Issue by JackandBlackLLL** [Ekultek/whitewidow#86]
Got mistake

root@kali:~/Desktop/w/whitewidow# ruby whitewidow.rb
Traceback (most recent call last):
	4: from whitewidow.rb:2:in `<main>'
	3: from whitewidow.rb:2:in `require_relative'
	2: from /root/Desktop/w/whitewidow/lib/imports/constants_and_requires.rb:3:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- mechanize (LoadError)

pls help

**Comment by JackandBlackLLL** [comment]
Fixed this problem, but now get, with any comands

[09:51:08 ERROR] Failed with error code (/root/Desktop/w/whitewidow/lib/lists/inject.yml): found unknown escape character while parsing a quoted scalar at line 19 column 19
[09:51:08 FATAL] Program failed with error code: (/root/Desktop/w/whitewidow/lib/lists/inject.yml): found unknown escape character while parsing a quoted scalar at line 19 column 19, error saved to error_log.txt
[09:51:08 FATAL] Issue template is being generated for this error, create a new issue named: 1g8Bgk2 (/root/Desktop/w/whitewidow/lib/lists/inject.yml): found unknown escape character while parsing a quoted scalar at line 19 column 19
